"use client";

import { useState } from "react";
import { GameShell } from "./GameShell";
import { DEFAULT_CASE } from "../lib/localCaseGenerator";
import { caseGeneratorService } from "../services/caseGeneratorService";
import type { CityCase, ProviderMode } from "../types/game";
import type { MissionReport } from "../types/game";

export function App({ embedded = false, studentName, onMissionComplete }: { embedded?: boolean; studentName?: string; onMissionComplete?: (report: MissionReport) => void | Promise<void> }) {
  const [caseData, setCaseData] = useState<CityCase>(DEFAULT_CASE); const [provider, setProvider] = useState<ProviderMode>("local"); const [modeStatus, setModeStatus] = useState("Local Case Generation"); const [notice, setNotice] = useState(""); const [loading, setLoading] = useState(false); const [playing, setPlaying] = useState(false); const [help, setHelp] = useState(false);
  const generate = async (startAfter = false) => {
    setLoading(true); setNotice("");
    const result = await caseGeneratorService.generate(provider);
    setCaseData(result.caseData); setModeStatus(result.status); setNotice(result.notice ?? "Kasus baru siap dimainkan."); setLoading(false);
    if (startAfter) setPlaying(true); else setPlaying(false);
  };
  if (playing) return <GameShell key={caseData.id} caseData={caseData} modeStatus={modeStatus} onReset={() => setPlaying(false)} onNewCase={() => generate(true)} studentName={studentName} onMissionComplete={onMissionComplete} />;
  return <main className={`landing-page pixel-game-theme ${embedded ? "embedded-game" : ""}`}><header className="landing-header"><div className="brand-static"><span className="brand-mark"><i /><b /><em /></span><span><strong>EcoMath Mission</strong><small>Sustainability City Challenge</small></span></div><div className="landing-badges"><span className="mode-status"><i />{modeStatus}</span><span className="sdg-pill">SDG 11</span><span className="sdg-pill blue">SDG 13</span></div></header>
    <section className="hero"><div className="hero-copy"><span className="kicker"><i /> ORIGINAL ISOMETRIC CITY SIM · SPtLDV</span><h1>EcoMath Mission.<br /><em>Bangun kota berkelanjutan.</em></h1><p>Jadilah perencana kota dan selesaikan misi pembangunan berkelanjutan melalui empat langkah Polya. Setiap keputusan menjadi bukti kemampuan pemecahan masalahmu.</p><div className="hero-actions account-actions">{embedded ? <button className="primary-btn jumbo" onClick={() => setPlaying(true)}>▶ MULAI MISI</button> : <><a className="primary-btn jumbo" href="/portal?role=student">🎒 MASUK SISWA</a><a className="secondary-btn jumbo" href="/portal?role=teacher">📋 PORTAL GURU</a></>}<button className="secondary-btn jumbo" onClick={() => setHelp(true)}>? PANDUAN</button></div>{!embedded && <button className="guest-play" onClick={() => setPlaying(true)}>Coba satu misi tanpa menyimpan laporan →</button>}
      <div className="generator-box"><div><small>GENERATOR KASUS</small><div className="provider-toggle"><button className={provider === "local" ? "active" : ""} onClick={() => setProvider("local")}>Local</button><button className={provider === "ai" ? "active" : ""} onClick={() => setProvider("ai")}>AI <small>if available</small></button></div></div><button className="generate-link" onClick={() => generate(false)} disabled={loading}><span className={loading ? "spin" : ""}>↻</span>{loading ? "Menyiapkan…" : "Generate kasus baru"}</button></div>
      {notice && <div className={notice.startsWith("AI unavailable") ? "landing-notice warning" : "landing-notice"}>{notice}</div>}
      <div className="microcopy"><span>✓ Offline-first</span><span>✓ 4 skor Polya</span><span>✓ Evidence log</span><span>✓ Tanpa API key browser</span></div>
    </div>
    <div className="hero-visual"><div className="visual-halo" /><span className="pixel-cloud cloud-a"/><span className="pixel-cloud cloud-b"/><div className="float-card mission"><span>◎</span><div><small>MISI SAAT INI</small><strong>{caseData.cityName}</strong></div></div><div className="city-board"><div className="terrain-patch patch-a"/><div className="terrain-patch patch-b"/><div className="road horizontal"/><div className="road vertical"/><div className="css-building a"><i/><i/><i/></div><div className="css-building b"><i/><i/></div><div className="css-building c"><i/><i/></div><div className="css-tree one"><i/></div><div className="css-tree two"><i/></div><div className="blue-route"><i/><b/><em/></div></div><div className="float-card target"><div className="target-ring">100</div><div><small>TARGET SKOR</small><strong>4 langkah Polya</strong></div></div><div className="pixel-mini-hud"><span><small>KAS</small><b>{caseData.constraints.find((item) => item.type === "budget")?.limit ?? 0} M</b></span><span><small>LAHAN</small><b>{caseData.constraints.find((item) => item.type === "land")?.limit ?? 0}</b></span><span><small>EMISI</small><b>{caseData.constraints.find((item) => item.type === "emission")?.limit ?? 0}</b></span></div><article className="case-preview"><div><span className="difficulty">{caseData.difficulty}</span><small>KASUS AKTIF</small></div><h2>{caseData.title}</h2><p>{caseData.initialCondition}</p><footer>{caseData.sdgFocus.map((item) => <span key={item}>{item.split("·")[0]}</span>)}</footer></article></div></section>
    <footer className="page-footer"><span>EcoMath Mission</span><i>•</i><span>Evidence-Centered Design</span><i>•</i><span>SDG 11 & 13</span></footer>
    {help && <div className="modal-backdrop" onMouseDown={() => setHelp(false)}><section className="help-modal" role="dialog" aria-modal="true" aria-labelledby="help-title" onMouseDown={(e) => e.stopPropagation()}><button className="close-btn" aria-label="Tutup" onClick={() => setHelp(false)}>×</button><span className="kicker">CARA BERMAIN</span><h2 id="help-title">Satu misi, empat langkah berpikir</h2><ol><li><b>01</b><div><strong>Memahami masalah</strong><p>Pilah fakta, tujuan, dan kendala.</p></div></li><li><b>02</b><div><strong>Menyusun rencana</strong><p>Tentukan x, y, lalu bangun SPtLDV.</p></div></li><li><b>03</b><div><strong>Melaksanakan rencana</strong><p>Tempatkan bangunan dan cari solusi feasible terbaik.</p></div></li><li><b>04</b><div><strong>Melihat kembali</strong><p>Periksa kewajaran dan jelaskan bukti.</p></div></li></ol><button className="primary-btn full" onClick={() => { setHelp(false); setPlaying(true); }}>Saya siap mulai →</button></section></div>}
  </main>;
}
