import { buildFeedback } from "../lib/assessment";

export function ScoreSummary({ scores, onReplay, onNewCase, nextActionLabel = "Generate kasus baru →", missionLabel }: { scores: number[]; onReplay: () => void; onNewCase: () => void; nextActionLabel?: string; missionLabel?: string }) {
  const total = scores.reduce((sum, value) => sum + value, 0);
  const status = total >= 85 ? "Sangat baik" : total >= 70 ? "Baik" : total >= 55 ? "Cukup" : "Gagal";
  const labels = ["Scout briefing", "Blueprint", "Build phase", "Debrief"];
  const badge = total >= 85 ? "Master Planner" : total >= 70 ? "Resource Guardian" : total >= 55 ? "District Fixer" : "Rookie Planner";
  const bonus = scores[2] >= 20 ? "Build stabil" : scores[1] >= 20 ? "Blueprint rapi" : scores[0] >= 20 ? "Intel tajam" : "Perlu scan ulang";
  return <div className="modal-backdrop"><section className="result-modal game-reward-modal" role="dialog" aria-modal="true" aria-labelledby="result-title"><div className={`result-orbit ${status.toLowerCase().replace(" ", "-")}`}><strong>{total}</strong><span>/100</span></div><span className="kicker">{missionLabel ? `${missionLabel} CLEAR` : "MISI SELESAI"} · REPUTASI KOTA</span><h2 id="result-title">{status}</h2><p>Kota menerima reputasi dari pilihan, aturan, scan, revisi, dan keputusan akhir. Inilah reward dari cara bermainmu, bukan sekadar jawaban akhir.</p><div className="reward-badges"><span><small>BADGE</small><b>{badge}</b></span><span><small>BONUS</small><b>{bonus}</b></span></div><div className="result-bars">{scores.map((score, index) => <div key={labels[index]}><span>{index + 1}</span><div><b>{labels[index]}</b><i><em style={{ width: `${score * 4}%` }} /></i></div><strong>{score}/25</strong></div>)}</div><p className="student-result-feedback">🎮 Umpan balik strategi: {buildFeedback(scores)}</p><div className="result-actions"><button className="secondary-btn" onClick={onReplay}>Ulangi distrik ini</button><button className="primary-btn" onClick={onNewCase}>{nextActionLabel}</button></div></section></div>;
}
